/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function addScalarF64(input: Float64Array, scalar: number): Float64Array
export declare function mulScalarF64(input: Float64Array, scalar: number): Float64Array
export declare function addF64(left: Float64Array, right: Float64Array): Float64Array
export declare function addScalarF64Buffer(input: Float64Array, scalar: number, output: Buffer): Buffer
export declare function mulScalarF64Buffer(input: Float64Array, scalar: number, output: Buffer): Buffer
export declare function addF64Buffer(left: Float64Array, right: Float64Array, output: Buffer): Buffer
export declare function addScalarF64Buffers(input: Buffer, scalar: number, output: Buffer): Buffer
export declare function mulScalarF64Buffers(input: Buffer, scalar: number, output: Buffer): Buffer
export declare function addF64Buffers(left: Buffer, right: Buffer, output: Buffer): Buffer
export declare function transposeF64Buffer(input: Float64Array, rows: number, cols: number, output: Buffer): Buffer
